name: GDS
baseurl: ""
highlighter: true
future: false
markdown: redcarpet
exclude: [".htaccess", "jekyll", "jekyll.html","node_modules","docs","imgs/student.pxm","imgs/genesis-assets.sketch"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
